name: build-documentation

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install sphinx==3.4.0 sphinx-prompt sphinx_substitution_extensions sphinx_book_theme
    - name: Builds and checks
      run: |
          mkdir html
    - name: Archive build directory
      uses: actions/upload-artifact@v1
      with:
          name: html-documentation
          path: html