name: clang-format-pull-request

on:
  pull_request:
    branches:
      - release_oneDPL
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get clang-format
      run: sudo apt-get install -yqq clang-format-6.0

    - name: Applying clang-format for changed files
      run: |
        FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} | grep ^include | grep -v nanorange\.hpp\$ || true)
        echo $FILES | xargs -n1 -t -r clang-format-6.0 --style=file -i

    - name: Creating diff
      run: git diff > clang-format-diff.diff

    - name: Checking if diff is empty
      run: if [ -s clang-format-diff.diff ]; then cat clang-format-diff.diff; exit 1; fi
