name: clang-format-pull-request

on:
  pull_request:
    branches:
      - release_oneDPL
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get clang-format
      run: sudo apt-get install -yqq clang-format-6.0

    - name: Applying clang-format for changed files
      run: |
        MAIN_BRANCH_SHA=$(git merge-base main HEAD)
        FILES=$(git diff --name-only $MAIN_BRANCH_SHA | grep ^include | grep -v nanorange\.hpp\$)
        clang-format-6.0 -i -style=file $FILES

    - name: Creating diff
      run: git diff > clang-format-diff.diff

    - name: Checking if diff is empty
      run: if [ -s clang-format-diff.diff ]; then cat clang-format-diff.diff; exit 1; fi
